import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/styles/globals.css";
import NavbarDashboard from "@/components/NavbarDashboard";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-[100dvh] w-full flex ">
            <NavbarDashboard />
            {children}
        </main>
      </body>
    </html>
  );
}
