import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/styles/globals.css";
import { auth } from "@/auth";
import AdminDashboard from "./admin/(routes)/(home)/page";
import TeacherDashboard from "./teacher/(routes)/(home)/pages";
import StudentDashboard from "./student/(routes)/(home)/pages";
import AccessDenied from "./accessDenied";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardPage() {
  const session = await auth()
  const userRole = session?.user?.role 
 
  if (userRole === 'ADMIN') {
    return <AdminDashboard />
  } else if (userRole === 'TEACHER') {
    return <TeacherDashboard />
  }else if(userRole === 'STUDENT'){
    return <StudentDashboard />
  } 
  else {
    return <AccessDenied />
  }
}
