import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/styles/globals.css";
import NavbarDashboard from "@/components/NavbarDashboard";
import { auth } from "@/auth";
import AccessDenied from "../../accessDenied";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function AdminDashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session= await auth();
  if(session?.user.role !=='ADMIN'){
    return <AccessDenied/>
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-[100dvh] w-full flex ">
            <NavbarDashboard />
            {children}
        </main>
      </body>
    </html>
  );
}
