import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/styles/globals.css";
import { auth } from "@/auth";
import AccessDenied from "./accessDenied";
import AdminDashboard from "./(routes)/admin/(home)/page";
import TeacherDashboard from "./(routes)/teacher/(home)/page";
import StudentDashboard from "./(routes)/student/(home)/page";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardPage() {
  const session = await auth();
  const userRole = session?.user?.role;

  if (userRole === "ADMIN") {
    redirect("/dashboard/admin");
  } else if (userRole === "TEACHER") {
    redirect("/dashboard/teacher");
  } else if (userRole === "STUDENT") {
    redirect("/dashboard/student");
  } else {
    return <AccessDenied />;
  }
}
